version: '3.8'

services:
  web:
    image: srivani-trust-app
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
       - "8000:8000"

    environment:
      - NAME=SrivaniTrust
